CREATE TABLE IF NOT EXISTS posts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       text VARCHAR(10000) NOT NULL,
                       likes_count BIGINT NOT NULL DEFAULT 0,
                       comments_count BIGINT NOT NULL DEFAULT 0,
                       image_data VARBINARY,
                       image_content_type VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS post_tags (
                           post_id BIGINT NOT NULL,
                           tag VARCHAR(255) NOT NULL,
                           PRIMARY KEY (post_id, tag),
                           CONSTRAINT fk_post_tags_post
                               FOREIGN KEY (post_id)
                                   REFERENCES posts(id)
                                   ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          text VARCHAR(10000) NOT NULL,
                          post_id BIGINT NOT NULL,
                          CONSTRAINT fk_comments_post
                              FOREIGN KEY (post_id)
                                  REFERENCES posts(id)
                                  ON DELETE CASCADE
);